GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/64b59055fd9a5f7478347606


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name":"Amazing",
    "subscribeToChannel":"Web dev"
}

###

DELETE http://localhost:3000/subscribers/64b5900bfd9a5f7478347603